SELECT KEEPER_ID AS KeeperId,
		USER_CNAME AS CName,
		USER_ENAME AS EName,
		FORMAT(LEND_DATE, 'yyyy') AS BorrowYear,
		COUNT(KEEPER_ID) AS BorrowCnt

FROM BOOK_LEND_RECORD BLR

INNER JOIN MEMBER_M MM ON BLR.KEEPER_ID=MM.[USER_ID]

GROUP BY KEEPER_ID, USER_CNAME, USER_ENAME, FORMAT(LEND_DATE, 'yyyy')

ORDER BY KEEPER_ID