SELECT A.BookId,
		A.BookName,
		A.QTY

FROM (SELECT BD.BOOK_ID BookId,
			BD.BOOK_NAME BookName,
			COUNT(BOOK_NAME) QTY,
			RANK() OVER(ORDER BY COUNT(*) DESC) Seq

		FROM BOOK_LEND_RECORD BLR

		INNER JOIN BOOK_DATA BD ON BLR.BOOK_ID = BD.BOOK_ID

		GROUP BY BD.BOOK_ID, BOOK_NAME) A

WHERE A.Seq <= 5