SELECT A.Seq,
		A.BookClass,
		A.BookId,
		A.BookName,
		A.Cnt

FROM (SELECT BC.BOOK_CLASS_NAME AS BookClass,
			BD.BOOK_ID AS BookId,
			BD.BOOK_NAME AS BookName,
			COUNT(*) AS Cnt,
			RANK() OVER(PARTITION BY BC.BOOK_CLASS_NAME ORDER BY COUNT(*) DESC, COUNT(*)) Seq

		FROM BOOK_LEND_RECORD BLR

		INNER JOIN BOOK_DATA BD ON BLR.BOOK_ID = BD.BOOK_ID

		INNER JOIN BOOK_CLASS BC ON BD.BOOK_CLASS_ID = BC.BOOK_CLASS_ID

		GROUP BY BC.BOOK_CLASS_NAME, BD.BOOK_ID, BD.BOOK_NAME) A

WHERE A.Seq <= 3