SELECT A.ClassId,
		A.ClassName,
		SUM(CASE A.[Year] WHEN '2016' THEN A.Cnt ELSE 0 END) AS CNT2016,
		SUM(CASE A.[Year] WHEN '2017' THEN A.Cnt ELSE 0 END) AS CNT2017,
		SUM(CASE A.[Year] WHEN '2018' THEN A.Cnt ELSE 0 END) AS CNT2018,
		SUM(CASE A.[Year] WHEN '2019' THEN A.Cnt ELSE 0 END) AS CNT2019

FROM (SELECT BC.BOOK_CLASS_ID AS ClassId,
				BC.BOOK_CLASS_NAME AS ClassName,
				FORMAT(BLR.LEND_DATE, 'yyyy') AS [Year],
				COUNT(*) AS Cnt
		FROM BOOK_LEND_RECORD BLR
		INNER JOIN BOOK_DATA BD ON BLR.BOOK_ID = BD.BOOK_ID
		INNER JOIN BOOK_CLASS BC ON BD.BOOK_CLASS_ID = BC.BOOK_CLASS_ID
		GROUP BY BC.BOOK_CLASS_ID, BC.BOOK_CLASS_NAME, FORMAT(BLR.LEND_DATE, 'yyyy')) A

GROUP BY A.ClassId, A.ClassName

ORDER BY A.ClassId