SELECT P.ClassId,
		P.ClassName,
		ISNULL(P.[2016], 0) AS CNT2016,
		ISNULL(P.[2017], 0) AS CNT2017,
		ISNULL(P.[2018], 0) AS CNT2018,
		ISNULL(P.[2019], 0) AS CNT2019

FROM (SELECT BC.BOOK_CLASS_ID AS ClassId,
				BC.BOOK_CLASS_NAME AS ClassName,
				FORMAT(BLR.LEND_DATE, 'yyyy') AS [Year],
				COUNT(*) AS Cnt
		FROM BOOK_LEND_RECORD BLR
		INNER JOIN BOOK_DATA BD ON BLR.BOOK_ID = BD.BOOK_ID
		INNER JOIN BOOK_CLASS BC ON BD.BOOK_CLASS_ID = BC.BOOK_CLASS_ID
		GROUP BY BC.BOOK_CLASS_ID, BC.BOOK_CLASS_NAME, FORMAT(BLR.LEND_DATE, 'yyyy')) A

PIVOT(
	SUM(A.Cnt)
	FOR A.[Year] IN ([2016], [2017], [2018], [2019])
) AS P

ORDER BY P.ClassId