SELECT BD.BOOK_ID AS [書本 ID],
		FORMAT(BOOK_BOUGHT_DATE, 'yyyy/M/dd') AS [購書日期],
		FORMAT(LEND_DATE, 'yyyy/MM/dd') AS [借閱日期],
		BOOK_CLASS_NAME AS [書籍類別],
		[USER_ID] + '-' + USER_CNAME + '('+USER_ENAME + ')' AS [借閱人],
		BOOK_STATUS + '-' + CODE_NAME AS [狀態],
		BOOK_AMOUNT AS [購書金額]

FROM BOOK_LEND_RECORD BLR

INNER JOIN MEMBER_M MM ON BLR.KEEPER_ID = MM.[USER_ID]
INNER JOIN BOOK_DATA BD ON BLR.BOOK_ID = BD.BOOK_ID
INNER JOIN BOOK_CLASS BCL ON BD.BOOK_CLASS_ID = BCL.BOOK_CLASS_ID
INNER JOIN BOOK_CODE BCO ON BD.BOOK_STATUS = BCO.CODE_ID AND BCO.CODE_TYPE = 'BOOK_STATUS'

WHERE USER_CNAME = '李四' AND 

ORDER BY [書本 ID] DESC